### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [cy8018/TVPlayer.Android#2]
Did you choose any license for your app? I cannot find that information (also not in the source code). As you write the app is based on [Exoplayer](https://github.com/google/ExoPlayer): is it correct to assume Apache-2.0 license then for your app, too?

**Comment by cy8018** [comment]
Thanks for the heads up, I'm gonna go with MIT license.

**Comment by IzzySoft** [comment]
Thanks!
