### ISSUE TITLE
App just crashes on start with Android Go (8.1)

### ISSUE THREAD

**Issue by IzzySoft** [cy8018/TVPlayer.Android#4]
I just wanted to try your app on my test device (a Wiko Sunny 3, running Android Go 8.1). App starts up, shows an (empty) player screen, and a few minutes later simply crashes. Reproducibly. I've attached a logcat ("grep'd" to only tv_player entries) in the hope it helps. Contains 3+ crashes.

[tv_logcat.zip](https://github.com/cy8018/TVPlayer.Android/files/4469267/tv_logcat.zip)

**Comment by cy8018** [comment]
Hi,

I added exception handling code for that, at least the app should not crash now.
The reason for the exception is that you may have slow connection to the station list JSON file.
I also uploaded the JSON file on github.com, you can try use that. Simply replace the following line

    public static final String StationListUrl = "https://gitee.com/cy8018/Resources/raw/master/tv/tv_station_list.json";

to 

    public static final String StationListUrl = "https://raw.githubusercontent.com/cy8018/Resources/master/tv/tv_station_list.json";

in MainActivity (line 62).

**Comment by IzzySoft** [comment]
Thanks! But I'm no Android dev and thus have no dev environment – so while I definitely could replace those lines, it wouldn't help me as I couldn't build :wink: If there's an APK I could test, just let me know: I can deal with `adb install` for that (as the logs showed) :smile:

**Comment by cy8018** [comment]
No problem, try this APK inside the zip:
[TvPlayer.zip](https://github.com/cy8018/TVPlayer.Android/files/4473500/TvPlayer.zip)

**Comment by IzzySoft** [comment]
Thanks! Yes, that fixed the issue – now the station list is loaded. I see it only contains Chinese stations; is there a way to add one's own stations, or chose a different station list?

**Comment by cy8018** [comment]
I'm sorry, customized station list not supported yet, but I will consider add that feature. I'll let you know once that feature is ready. Thanks.

**Comment by IzzySoft** [comment]
Thanks, great! Looking forward to that then.

**Comment by cy8018** [comment]
You can now load your own m3u list via settings menu.

**Comment by IzzySoft** [comment]
With the next release – or with v2.2.2 already?

**Comment by cy8018** [comment]
Already.

**Comment by IzzySoft** [comment]
Thanks, great! I've just updated description and screenshots (will propagate with the next sync in about 6.5h from now to [go live here](https://apt.izzysoft.de/fdroid/index/apk/com.cy8018.tvplayer). Besides, if you wish to place a second badge next to the Google Play one, [I have one here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for those unable (or unwilling) to use Play. Updates are fetched within 24h of your releasing the APK, and users are notified via their local F-Droid clients.

Oh, and I've added your app to [my corresponding list](https://android.izzysoft.de/applists/category/named/multimedia_video_tv#group_351) to make people aware of it. Thanks again!

**Comment by cy8018** [comment]
Cool website!

**Comment by IzzySoft** [comment]
Thanks – glad you like it!

Just wondering, as my scanner just sent me a hint (to add the NonFreeNet and NonFreeDep): is the *Google Play Core* library really needed by the app? That binds it to non-free dependencies, so it would be good to avoid it in FOSS apps when possible.
